### ISSUE TITLE
Coveralls not displaying source code

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-pyhf-extractor#7]
If I inspect a Coveralls [build](https://coveralls.io/builds/34781021) and click a [source file](https://coveralls.io/builds/34781021/source?filename=src/pyhf_extractor/summarizers/pallet.py) to see which lines are not covered by tests, I get a message "SOURCE NOT AVAILABLE".  Viewing the source in Coveralls was quite useful when using Travis CI for the other HEPData repos.  Can this be fixed?

**Comment by GraemeWatt** [comment]
I can see the source code if I log in to Coveralls.  But for other repos, the source code is visible without logging in.

Note that coverage data is submitted to coveralls.io when you run the [coveralls](https://github.com/HEPData/hepdata-pyhf-extractor/blob/24728e53c03a584768a436ef455ad0f6cbd9cb60/.github/workflows/ci.yml#L63) command.  Therefore, I don't think you need to use the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action) in [these lines](https://github.com/HEPData/hepdata-pyhf-extractor/blob/24728e53c03a584768a436ef455ad0f6cbd9cb60/.github/workflows/ci.yml#L65-L73).  See the workflows for the [hepdata_lib](https://github.com/HEPData/hepdata_lib/blob/master/.github/workflows/coverage.yml) and [hepdata](https://github.com/HEPData/hepdata/blob/github-actions/.github/workflows/python-app.yml) repos, which just use `coveralls` and not the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action).  In both cases, the source code can be seen on coveralls.io without logging in, with covered lines shown in green and uncovered lines shown in red.

**Comment by GraemeWatt** [comment]
I've got this working now.  I needed to claim ownership of the repo at https://coveralls.io/github/HEPData/hepdata-pyhf-extractor/settings since Coveralls needs someone's GitHub OAuth credentials to pull the source code.  I'll close this issue.

**Comment by Sinclert** [comment]
Happy to hear the source code is been shown now!

Regarding the [Coveralls GitHub Action](https://github.com/marketplace/actions/coveralls-github-action), I understood that it is the necessary _wrap up_ when multiple coverage calculating jobs are executed in parallel. I am unsure if other HEPData repos also go through this CI behaviour.
